name: Daily WhatsApp Sender

on:
  schedule:
    - cron: "40 1 * * *"   # 02:40 UTC
  workflow_dispatch:

jobs:
  call-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel Daily Endpoint
        run: |
          curl -X GET "https://whatsappagent-hibas-projects-422342d6.vercel.app/api/daily/"
